[server]
# ip_address = "10.20.110.146"
ip_address = "localhost"

[security]
enable = true
timeout = 25

#[keystore]
#generate = false
#file = "mycert.jks"
#password = "password"

[mongo]
enable = true
uri = "mongodb://localhost:27017"
db = "dev"
UserRepo = "users"
PasswordRepo = "store"
