[server]
ip_address = "localhost"
https_port = 8080

[security]
enable = true
timeout = 15
password_timeout = 5
password_fails = 3

[mongo]
enable = true
uri = "mongodb://localhost:27017"
db = "dev"
UserRepo = "users"
PasswordRepo = "store"

